import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { machinery, machineryCategories } from './data/machinery';
import './styles.css';
import './catalogue.css';

const catalogue = '/machinery-warehouse-outlet-catalogue.pdf';
const contact = {
  telephone: ['081-670-95700', '081-857-69700', '080-331-30374', '080-868-34332'],
  email: ['machines.warehouse@juninet.com', 'machines.warehouse@gmail.com'],
  address: 'Awada Industrial Zone, 2, Ichi Street, Off Eziweka Road, Awada - Obosi, Anambra State.',
  branches: 'Lagos. Abuja.'
};

function Mark(){ return <a className="brand" href="#top" aria-label="Machinery Warehouse Outlet home"><span className="brand-m">M</span><span>achinery<br/><b>Warehouse Outlet</b></span></a> }
function Arrow(){ return <span className="arrow" aria-hidden="true">↗</span> }
function App(){
  const [menu, setMenu] = useState(false); const [query,setQuery] = useState(''); const [active,setActive] = useState('All'); const [quote,setQuote] = useState(null); const [detail,setDetail] = useState(null);
  const shown = machinery.filter(p => (active==='All'||p.category===active) && (p.name+p.model+p.category).toLowerCase().includes(query.toLowerCase()));
  useEffect(()=>{ document.body.style.overflow = menu ? 'hidden' : ''; return ()=>document.body.style.overflow=''; },[menu]);
  const openQuote=(product=null)=>{setQuote(product); setDetail(null); document.querySelector('#quote')?.scrollIntoView({behavior:'smooth'});};
  return <>
    <header className="nav" id="top"><Mark/><nav aria-label="Primary navigation"><a href="#machinery">Machinery</a><a href="#parts">Spare parts</a><a href="#about">About</a><a href="#catalogue">Catalogue</a><a href="#contact">Contact</a></nav><button className="nav-cta" onClick={()=>openQuote()}>Request a quote <Arrow/></button><button className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label="Toggle menu"><i></i><i></i></button></header>
    <div className={'mobile-menu '+(menu?'is-open':'')}><Mark/><nav><a onClick={()=>setMenu(false)} href="#machinery">Machinery</a><a onClick={()=>setMenu(false)} href="#parts">Spare parts</a><a onClick={()=>setMenu(false)} href="#about">About</a><a onClick={()=>setMenu(false)} href="#catalogue">Catalogue</a><a onClick={()=>setMenu(false)} href="#contact">Contact</a></nav><button onClick={()=>{setMenu(false);openQuote()}}>Request a quote <Arrow/></button></div>
    <main>
      <section className="hero"><div className="hero-copy"><p className="eyebrow light">Machinery Warehouse Outlet</p><h1>Industrial machinery.<br/><em>Purposefully supplied.</em></h1><p className="hero-text">A focused catalogue of machinery for plastics, packaging, water packaging and fuel dispensing — with spare parts and accessories.</p><div className="hero-actions"><a className="button primary" href="#machinery">Explore machinery <Arrow/></a><button className="button ghost" onClick={()=>openQuote()}>Request a quote</button></div></div><div className="hero-visual"><div className="technical-note"><span>01 / FILM PRODUCTION</span><span>MWO · CATALOGUE</span></div><img src={`${import.meta.env.BASE_URL}assets/machine-images/IMG_1759.jpeg`} alt="Three-layer co-extrusion film blowing machine"/><div className="hero-label"><b>Featured system</b><span>Three-layer co-extrusion IBC film blowing machine</span></div></div><div className="scroll-cue">SCROLL TO EXPLORE <span></span></div></section>
      <section className="intro"><p className="eyebrow">01 — What we supply</p><div><h2>Equipment for the work that moves production forward.</h2><p>The supplied catalogue covers machinery for plastic production, packaging, water packaging, fuel dispensing and related spare parts.</p></div></section>
      <section className="categories"><a href="#machinery"><span>01</span><b>Plastic<br/>Machines</b><Arrow/></a><a href="#machinery"><span>02</span><b>Poly Packaging<br/>Machines</b><Arrow/></a><a href="#machinery"><span>03</span><b>Water Packaging<br/>Machines</b><Arrow/></a><a href="#machinery"><span>04</span><b>Fuel Dispensing<br/>Machines</b><Arrow/></a></section>
      <section className="machinery" id="machinery"><div className="section-heading"><div><p className="eyebrow">02 — Machinery catalogue</p><h2>Find the right<br/><em>machine.</em></h2></div><p>Browse every machine and product presented in the company catalogue. Search by name, model, or category.</p></div><div className="catalogue-controls"><label><span>⌕</span><input aria-label="Search machinery" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search machinery or model"/></label><div className="filters">{machineryCategories.map(c=><button key={c} className={c===active?'active':''} onClick={()=>setActive(c)}>{c}</button>)}</div></div><p className="result-count">Showing {shown.length} of {machinery.length} catalogue products</p><div className="product-grid">{shown.map((p,i)=><article className="product" key={p.id}><div className="product-image"><img loading="lazy" src={p.image} alt={p.name}/><span>{String(i+1).padStart(2,'0')}</span></div><div className="product-info"><p>{p.category}</p><h3>{p.name}</h3>{p.model && <small><b>Model:</b> {p.model}</small>}<div><button onClick={()=>openQuote(p)}>Request quote <Arrow/></button><button className="text-link" onClick={()=>setDetail(p)}>View details</button></div></div></article>)}</div>{!shown.length&&<div className="empty"><p>No machinery found.</p><button onClick={()=>{setQuery('');setActive('All')}}>Reset catalogue</button></div>}</section>
      <section className="statement" id="about"><div><p className="eyebrow light">03 — Built around the catalogue</p><h2>Quality<br/><em>guaranteed.</em></h2></div><p>Machinery Warehouse Outlet presents industrial machines and spare parts across practical production categories. View the original catalogue for the complete visual reference.</p></section>
      <section className="parts" id="parts"><div className="parts-image"><img src={`${import.meta.env.BASE_URL}assets/machine-images/IMG_1779.jpeg`} alt="Accessories and moulds for plastic machinery"/></div><div><p className="eyebrow">04 — Spare parts & accessories</p><h2>Keep the operation in motion.</h2><p>The catalogue includes spare parts and accessories, along with accessories and moulds for blow moulding and plastic injection machines.</p><button className="line-button" onClick={()=>openQuote({name:'Accessories and Moulds for Blow Moulding and Plastic Injection Machines',model:'Not stated in supplied image'})}>Enquire about spare parts <Arrow/></button></div></section>
      <section className="catalogue-panel" id="catalogue"><div className="catalogue-sheet"><div className="sheet-mark"><Mark/></div><p>COMPANY CATALOGUE</p><span>INDUSTRIAL MACHINES<br/>AND SPARE PARTS</span></div><div><p className="eyebrow">05 — Catalogue</p><h2>The complete<br/><em>reference.</em></h2><p>Explore the original Machinery Warehouse Outlet catalogue, including product imagery and listed models.</p><div className="hero-actions"><a className="button primary" href={catalogue} target="_blank" rel="noreferrer">View catalogue <Arrow/></a><a className="button ghost dark" href={catalogue} download>Download PDF</a></div></div></section>
      <section className="quote" id="quote"><div><p className="eyebrow light">06 — Make an enquiry</p><h2>Let’s discuss<br/><em>your requirement.</em></h2><p>Tell us what you are looking for and the team can follow up using the contact details below.</p></div><form onSubmit={e=>{e.preventDefault(); alert('Your enquiry is ready to be connected to the company’s preferred form service.');}}><label>Name<input required name="name" autoComplete="name"/></label><label>Company<input name="company" autoComplete="organization"/></label><label>Phone<input required name="phone" type="tel" autoComplete="tel"/></label><label>Email<input required name="email" type="email" autoComplete="email"/></label><label className="wide">Machine / product<input value={quote?.name||''} onChange={e=>setQuote({name:e.target.value,model:''})} placeholder="Select from catalogue or enter a product"/></label>{quote?.model&&<label className="wide">Model<input readOnly value={quote.model}/></label>}<label className="wide">Message<textarea name="message" rows="3" placeholder="Tell us about your requirement"/></label><button className="submit" type="submit">Send enquiry <Arrow/></button><small className="form-note">Frontend integration point — connect this form to your preferred email or CRM service before publishing.</small></form></section>
    </main>{detail&&<div className="product-dialog" role="dialog" aria-modal="true" aria-label={detail.name}><button className="dialog-close" onClick={()=>setDetail(null)} aria-label="Close details">×</button><div className="dialog-image"><img src={detail.image} alt={detail.name}/></div><div className="dialog-copy"><p className="eyebrow">{detail.category}</p><h2>{detail.name}</h2>{detail.model&&<p className="dialog-model">Model: {detail.model}</p>}<p>Catalogue product reference.</p><button className="button primary" onClick={()=>openQuote(detail)}>Request a quote <Arrow/></button></div></div>}
    <footer id="contact"><div className="footer-top"><Mark/><p>Home of industrial machines and spare parts.</p><a href="#quote">Request a quote <Arrow/></a></div><div className="footer-grid"><div><p className="footer-label">Telephone</p>{contact.telephone.map(n=><a href={'tel:'+n.replace(/-/g,'')} key={n}>{n}</a>)}</div><div><p className="footer-label">Email</p>{contact.email.map(n=><a href={'mailto:'+n} key={n}>{n}</a>)}</div><div><p className="footer-label">Contact address</p><address>{contact.address}</address><p className="branches">Branches: {contact.branches}</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Machinery Warehouse Outlet</span><span>All product information is sourced from the supplied catalogue.</span></div></footer>
  </>
}
createRoot(document.getElementById('root')).render(<App/>);
